# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e062bf05189fe6393632a4ec08548475cc3f65e2c6ca890cdcc1c603ed09d3ee5ac7c8182da1970854409eb300541ada374153f1b966e8cfc31095c83ffb288b

test:
  secret_key_base: 1d14c7603e8cd221c496fa5cdabc87375498474e36b19b339b9388071de06d4b56ee40f317d37c6b30f2760cbc16adb9b3cea517badf744e235234e0f7c99f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
